name: firestore_ui
description: A port of firebase_database's FirebaseAnimatedList that works with cloud_firestore, with additional variants
version: 1.13.0
homepage: https://github.com/gildaswise/firestore_ui
# author: Gildásio Filho <gildasiogx@gmail.com>

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.1.6 
  firebase_core: ^1.0.2
  cloud_firestore: ^1.0.2
  flutter_staggered_grid_view: ^0.3.2
  collection: ^1.14.13

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
